# Generated by Django 5.0.6 on 2025-01-02 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliver_transactions', to='troca.customer'),
        ),
    ]
