# Generated by Django 5.0.6 on 2025-01-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troca', '0002_alter_transaction_completed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
