# Generated by Django 5.0.6 on 2025-01-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('troca', '0003_alter_transaction_date_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date_completed',
            new_name='completed_date',
        ),
    ]
