# Generated by Django 5.0.6 on 2025-01-14 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troca', '0004_rename_date_completed_transaction_completed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deliver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='troca.deliver'),
        ),
    ]
