# Generated by Django 5.0.6 on 2025-01-14 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troca', '0005_deliver_transaction_is_charge_transaction_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='deliver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='troca.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deliver',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Deliver',
        ),
    ]
