# Generated by Django 5.0.6 on 2025-01-15 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('troca', '0006_alter_transaction_deliver_customer_is_deliver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='deliver',
        ),
    ]
