# Generated by Django 5.0.6 on 2025-01-18 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troca', '0009_alter_friendpayment_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendpayment',
            name='boss',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='friend_payments', to='troca.customer'),
            preserve_default=False,
        ),
    ]
