# Generated by Django 5.0.6 on 2025-01-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troca', '0010_friendpayment_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendpayment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
