# Generated by Django 5.1.7 on 2025-04-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('troca', '0012_client_product_payment_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='client',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='product',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
