# Generated by Django 5.0 on 2026-04-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('troca', '0013_remove_sell_client_remove_sell_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendpayment',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friendpayment',
            name='boss',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='friend_paid',
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='FriendPayment',
        ),
    ]
