# Generated by Django 4.2.7 on 2024-03-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokens',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
