server {
    listen 80;

    # Fix: This special loop tells Nginx to look directly at the Linux host network DNS config
    resolver 127.0.0.11 ipv6=off;
    
    # Alternative for Railway Core mesh networks if the above fails:
    # resolver 100.64.0.1 valid=5s;

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_redirect off;

    location / {
        set $cms_url "http://railway.internal";
        proxy_pass $cms_url;
    }

    location /cms/ {
        set $cms_url "http://railway.internal/";
        proxy_pass $cms_url;
    }

    location /tour/ {
        set $tour_url "http://railway.internal";
        proxy_pass $tour_url; 
    }

    location /remittance/ {
        set $remittance_url "http://railway.internal";
        proxy_pass $remittance_url; 
    }

    location /certificate/ {
        set $cert_url "http://railway.internal";
        proxy_pass $cert_url; 
    }
    
    location /static/ {
        alias /home/app/web/staticfiles/;
    }
}
