server {
    # Escuta na porta dinâmica injetada pela Railway
    listen ${PORT}; 

    # Aceita tráfego do domínio raiz e subdomínios wildcards
    server_name teladoshi.com *.teladoshi.com;

    # DNS interno do Docker/Railway para atualizar IPs dos containers
    # resolver 127.0.0.11 valid=30s;

    # Cabeçalhos cruciais para o django-tenants identificar subdomínios
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_redirect off;

    # Rota raiz (Fallback para o CMS)
    location / {
        proxy_pass http://${CMS_URL};
    }

    # Central Management System (CMS)
    location /cms/ {
        proxy_pass http://${CMS_URL}/;
    }

    # Motor de Turismo
    location /tour/ {
        proxy_pass http://${TOUR_URL}/; 
    }

    # Pipeline de Remessas Financeiras
    location /remittance/ {
        proxy_pass http://${REMITTANCE_URL}/; 
    }

    # Motor de Certificados e Validação Criptográfica
    location /certificate/ {
        proxy_pass http://${CERTIFICATE_URL}/; 
    }
    
    # Entrega de arquivos estáticos globais (CSS, JS, Imagens)
    location /static/ {
        alias /home/app/web/staticfiles/;
    }
}
