# Generated by Django 4.2.4 on 2023-10-19 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
    ]
