# Generated by Django 4.2.7 on 2024-03-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_user_code_remove_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=50)),
                ("token", models.CharField(max_length=50)),
            ],
        ),
    ]
