# Generated by Django 4.2.7 on 2024-03-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_usertokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertokens",
            name="email",
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
