# Generated by Django 4.2.7 on 2024-03-24 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_usertokens_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserTokens",
        ),
    ]
