# Generated by Django 4.2.7 on 2024-03-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_delete_usertokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="parthner",
            field=models.IntegerField(default=1),
        ),
    ]
