# Generated by Django 4.2.7 on 2024-03-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_user_parthner"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
