# Generated by Django 4.2.7 on 2024-03-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="valid",
            field=models.BooleanField(default=False),
        ),
    ]
