# Generated by Django 4.2.7 on 2024-03-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_user_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="parthner",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
