# Generated by Django 4.2.7 on 2024-03-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_user_parthner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
