# Generated by Django 5.0.6 on 2024-12-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="backstaff",
            field=models.BooleanField(default=False),
        ),
    ]
