# Generated by Django 5.0.6 on 2025-01-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_user_backstaff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="parthner",
            field=models.IntegerField(null=True),
        ),
    ]
