# Generated by Django 5.0 on 2026-03-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_user_parthner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("domain", models.CharField(max_length=50, unique=True)),
                ("subdomain", models.CharField(max_length=50, null=True, unique=True)),
                ("has_blog", models.BooleanField(default=False)),
            ],
        ),
    ]
