# Generated by Django 5.0 on 2026-03-15 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_tenant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tenant",
            old_name="has_blog",
            new_name="has_cms",
        ),
    ]
