# Generated by Django 5.0 on 2026-03-15 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0014_rename_has_blog_tenant_has_cms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.RemoveField(
            model_name="user",
            name="backstaff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="parthner",
        ),
        migrations.AddField(
            model_name="tenant",
            name="contact_email",
            field=models.CharField(default="edmilbe@gmail.com", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenant",
            name="contact_phone",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="email_password",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenant",
            name="logo",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="partner",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", False)),
                fields=("email", "tenant"),
                name="unique_email_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone__isnull", False)),
                fields=("phone", "tenant"),
                name="unique_phone_per_tenant",
            ),
        ),
    ]
