# Generated by Django 5.0 on 2026-04-08 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_user_tenant"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
