# Generated by Django 5.0 on 2026-05-06 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_domain_tenant_alter_user_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app",
                    models.CharField(
                        choices=[
                            ("certificates", "Certificates"),
                            ("troca", "Troca"),
                            ("cms", "Cms"),
                        ],
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_apps",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "app")},
            },
        ),
    ]
