# Generated by Django 5.0 on 2026-05-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_clientapp_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientapp",
            name="app",
            field=models.CharField(
                choices=[
                    ("cms", "Cms"),
                    ("certificates", "Certificates"),
                    ("troca", "Troca"),
                    ("teladoshi", "Teladoshi"),
                ],
                max_length=100,
            ),
        ),
    ]
