# Generated by Django 5.0 on 2026-05-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_clientapp_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientapp",
            name="app",
            field=models.CharField(
                choices=[
                    ("cms", "Cms"),
                    ("certificates", "Certificates"),
                    ("troca", "Troca"),
                    ("teladoshi", "Teladoshi"),
                    ("order", "Order"),
                ],
                max_length=100,
            ),
        ),
    ]
