# Generated by Django 4.2.7 on 2024-03-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_alter_usertokens_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokens',
            name='token',
            field=models.UUIDField(),
        ),
    ]
