# Generated by Django 5.0 on 2026-03-17 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_alter_user_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registered', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('number_of_associated', models.IntegerField()),
                ('picture', models.FileField(upload_to='mt_api/cms/association_images')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='core.tenant')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='cms.district')),
            ],
        ),
        migrations.CreateModel(
            name='AssociationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='mt_api/cms/association_images/')),
                ('associaton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.association')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_images', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('text_file', models.FileField(upload_to='mt_api/cms/docs/documents/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('B', 'Budget'), ('R', 'Report'), ('L', 'Law')], max_length=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('picture', models.FileField(null=True, upload_to='mt_api/cms/posts/images/')),
                ('text_file', models.FileField(upload_to='mt_api/cms/posts/documents/')),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_docs', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='mt_api/cms/extras/images/')),
                ('extra_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='cms.extradoc')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('sent', models.BooleanField(blank=True, default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('picture', models.FileField(upload_to='mt_api/cms/partner_images/')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('picture', models.FileField(upload_to='mt_api/cms/posts/images/')),
                ('text_file', models.FileField(null=True, upload_to='mt_api/cms/posts/documents/')),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_a_service', models.BooleanField(default=False)),
                ('is_social_service', models.BooleanField(default=False)),
                ('is_to_front', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='Através desse seviço, estarás habilitado para ...', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('question', models.CharField(max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='core.tenant')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informations', to='cms.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='mt_api/cms/post/documents/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cms.post')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_documents', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mt_api/cms/posts/file/')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_files', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='mt_api/cms/posts/images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='cms.post')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretaries', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SecreatarySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretary_sections', to='core.tenant')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secreatary_sections', to='cms.secretary')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secreatary_sections', to='cms.section')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='mt_api/cms/tour/images/')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_tours', to='core.tenant')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('picture', models.FileField(blank=True, null=True, upload_to='mt_api/cms/video_images/')),
                ('is_band', models.BooleanField(default=False)),
                ('is_spot', models.BooleanField(default=False)),
                ('created_at', models.DateField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_videos', to='cms.post')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_videos', to='core.tenant')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_videos', to='cms.video')),
            ],
        ),
        migrations.CreateModel(
            name='YearGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('associations', models.IntegerField()),
                ('agricultors', models.IntegerField()),
                ('products', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_goals', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(null=True, upload_to='mt_api/cms/team/images/')),
                ('from_assembly', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='cms.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.tenant')),
            ],
            options={
                'unique_together': {('name', 'role', 'tenant')},
            },
        ),
    ]
