# Generated by Django 5.0 on 2026-03-17 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('core', '0017_alter_user_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_associations', to='cms.district'),
        ),
        migrations.AlterField(
            model_name='association',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_associations', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='associationimages',
            name='associaton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_images', to='cms.association'),
        ),
        migrations.AlterField(
            model_name='associationimages',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_association_images', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_budgets', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='extradoc',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_extra_docs', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='extraimages',
            name='extra_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_extra_images', to='cms.extradoc'),
        ),
        migrations.AlterField(
            model_name='extraimages',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_extra_images', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='imagestour',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_images_tours', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='imagestour',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_images', to='cms.tour'),
        ),
        migrations.AlterField(
            model_name='information',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cms_informations', to='cms.post'),
        ),
        migrations.AlterField(
            model_name='information',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_informations', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='message',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_messages', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_partner', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_posts', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postdocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_post_documents', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_post_files', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_post_images', to='cms.post'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_post_images', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_post_videos', to='cms.post'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_post_videos', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_post_videos', to='cms.video'),
        ),
        migrations.AlterField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_role', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='secreatarysection',
            name='secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_secreatary_sections', to='cms.secretary'),
        ),
        migrations.AlterField(
            model_name='secreatarysection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_secreatary_sections', to='cms.section'),
        ),
        migrations.AlterField(
            model_name='secreatarysection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_secretary_sections', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_secretaries', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_secretaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_sections', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_teams', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_tours', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_videos', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='yeargoals',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_year_goals', to='core.tenant'),
        ),
    ]
