# Generated by Django 5.0 on 2026-03-17 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_association_district_alter_association_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informations', to='cms.post'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='cms.post'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_videos', to='cms.post'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_videos', to='cms.video'),
        ),
        migrations.AlterField(
            model_name='secreatarysection',
            name='secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secreatary_sections', to='cms.secretary'),
        ),
        migrations.AlterField(
            model_name='secreatarysection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secreatary_sections', to='cms.section'),
        ),
    ]
