# Generated by Django 5.0 on 2026-03-17 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_information_service_alter_postimage_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfile',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cms_files', to='cms.post'),
            preserve_default=False,
        ),
    ]
