# Generated by Django 5.0 on 2026-03-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_postfile_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='processed_text_file',
            field=models.FileField(blank=True, help_text='Auto-generated JSON file with processed HTML content', null=True, upload_to='mt_api/cms/posts/processed/'),
        ),
    ]
