# Generated by Django 5.0 on 2026-03-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_post_processed_text_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='processed_text_file',
            field=models.FileField(blank=True, help_text='Auto-generated JSON file with processed HTML content', max_length=500, null=True, upload_to='mt_api/cms/posts/processed/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='mt_api/cms/posts/documents/'),
        ),
    ]
