# Generated by Django 5.0 on 2026-04-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='review', max_length=255),
            preserve_default=False,
        ),
    ]
