# Generated by Django 5.0 on 2026-04-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
