# Generated by Django 5.0 on 2026-04-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_post_post_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='text',
        ),
    ]
