# Generated by Django 5.0 on 2026-04-26 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_rename_post_text_post_text'),
        ('core', '0019_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.SlugField(max_length=255)),
                ('file', models.FileField(upload_to='mt_api/cms/laws/file/')),
                ('published_date', models.DateField()),
                ('aprovation_date', models.DateField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_laws', to='core.tenant')),
                ('an_president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_laws_an_president', to='cms.president')),
                ('stp_president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_laws_stp_president', to='cms.president')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField()),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_laws_votes_law', to='cms.law')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_laws_votes_party', to='cms.party')),
            ],
        ),
    ]
