# Generated by Django 5.0 on 2026-04-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_party_president_law_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='law',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='president',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='president',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('party', 'law')},
        ),
    ]
