# Generated by Django 5.0 on 2026-05-06 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_alter_law_slug_alter_law_title_alter_party_name_and_more'),
        ('core', '0021_alter_domain_tenant_alter_user_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_associations', to='core.client'),
        ),
        migrations.AlterField(
            model_name='associationimages',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_association_images', to='core.client'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_budgets', to='core.client'),
        ),
        migrations.AlterField(
            model_name='extradoc',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_extra_docs', to='core.client'),
        ),
        migrations.AlterField(
            model_name='extraimages',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_extra_images', to='core.client'),
        ),
        migrations.AlterField(
            model_name='imagestour',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_images_tours', to='core.client'),
        ),
        migrations.AlterField(
            model_name='information',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_informations', to='core.client'),
        ),
        migrations.AlterField(
            model_name='law',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_laws', to='core.client'),
        ),
        migrations.AlterField(
            model_name='message',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_messages', to='core.client'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_partner', to='core.client'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_posts', to='core.client'),
        ),
        migrations.AlterField(
            model_name='postdocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_post_documents', to='core.client'),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_post_files', to='core.client'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_post_images', to='core.client'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_post_videos', to='core.client'),
        ),
        migrations.AlterField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_role', to='core.client'),
        ),
        migrations.AlterField(
            model_name='secreatarysection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_secretary_sections', to='core.client'),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_secretaries', to='core.client'),
        ),
        migrations.AlterField(
            model_name='section',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_sections', to='core.client'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_teams', to='core.client'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_tours', to='core.client'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_videos', to='core.client'),
        ),
        migrations.AlterField(
            model_name='yeargoals',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_year_goals', to='core.client'),
        ),
    ]
