# Generated by Django 5.0 on 2026-06-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tenant',
        ),
    ]
