# Generated by Django 5.0 on 2026-06-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_remove_post_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
