# Generated by Django 5.0 on 2026-06-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_post_text_en_post_text_pt_post_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_pt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_pt',
        ),
    ]
