# Generated by Django 4.2.4 on 2023-10-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
