# Generated by Django 4.2.4 on 2023-10-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_person_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_expire_date',
            field=models.DateField(null=True),
        ),
    ]
