# Generated by Django 4.2.4 on 2023-10-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_alter_person_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_issue_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_issue_person', to='certificates.country'),
        ),
    ]
