# Generated by Django 4.2.4 on 2023-10-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_alter_person_id_issue_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_nationality', to='certificates.country'),
        ),
    ]
