# Generated by Django 4.2.4 on 2023-10-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_alter_person_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetitle',
            name='type_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
