# Generated by Django 4.2.4 on 2023-10-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_alter_certificatetitle_certificate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetypes',
            name='gender',
            field=models.CharField(choices=[('o', 'o'), ('a', 'a')], default='o', max_length=1, null=True),
        ),
    ]
