# Generated by Django 4.2.4 on 2023-10-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_alter_certificatetypes_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='type1',
            new_name='typeid1',
        ),
    ]
