# Generated by Django 4.2.4 on 2023-10-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0010_rename_type1_certificate_typeid1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='typeid1',
            new_name='type_id1',
        ),
    ]
