# Generated by Django 4.2.4 on 2023-10-24 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0011_rename_typeid1_certificate_type_id1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_issue',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='main_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_person_certificates', to='certificates.person'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('C', 'Completo'), ('F', 'Incorrecto'), ('P', 'Pendente')], default='P', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='text',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.certificatetitle'),
        ),
    ]
