# Generated by Django 4.2.4 on 2023-10-24 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0012_alter_certificate_date_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.county'),
        ),
    ]
