# Generated by Django 4.2.4 on 2023-11-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0013_street_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('C', 'Completo'), ('F', 'Incorrecto'), ('R', 'Pendente'), ('R', 'Revisto')], default='R', max_length=1, null=True),
        ),
    ]
