[pytest]
DJANGO_SETTINGS_MODULE = camaramz.settings.test
python_files = tests.py test_*.py *_tests.py
# Added --cov-append flag to safely combine data from all 4 workers
addopts = -p no:warnings --create-db --cov=teladoshi --cov=order --cov-report=term-missing --cov-append

[coverage:run]
branch = True
concurrency = multiprocessing
parallel = True
omit =
  *apps.py,
  *settings.py,
  *urls.py,
  *wsgi.py,
  *asgi.py,
  manage.py,
  */migrations/*,
  */tests/*
