import pytest
from django.apps import apps
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType

from order.serializers import (
    BookingItemSerializer,
    BookingSerializer,
    CartItemSerializer,
    CartSerializer,
    ReviewSerializer,
    SMSOutgoingQueueSerializer,
)

User = get_user_model()

# Dynamically resolve models without static import calls
VendorModel = apps.get_model("teladoshi", "Vendor")
CustomerModel = apps.get_model("order", "Customer")
BookingModel = apps.get_model("order", "Booking")


# --- 1. CART SERIALIZER TESTS ---

@pytest.mark.django_db
def test_cart_serializer(new_cart, new_cart_item):
    """Tests serialization of a Cart model along with its nested CartItems."""
    cart = new_cart()
    cart.save()

    mock_service = VendorModel.objects.create(company_name="Serializer Service")

    item1 = new_cart_item(cart=cart, content_object=mock_service, days=2)
    item1.save()
    item2 = new_cart_item(cart=cart, content_object=mock_service, days=5)
    item2.save()

    serializer = CartSerializer(instance=cart)
    data = serializer.data

    assert data["id"] == str(cart.id)
    assert "created_at" in data
    assert len(data["items"]) == 2
    assert data["items"][0]["id"] == item1.id
    assert data["items"][0]["days"] == 2
    assert data["items"][1]["days"] == 5


@pytest.mark.django_db
def test_cart_item_serializer_creation():
    """Validates direct instantiation, validation, and popping of model_type tags."""
    mock_service = VendorModel.objects.create(company_name="Transient Item Check")

    valid_payload = {
        "model_type": "vendor",
        "object_id": mock_service.id,
        "days": 4,
        "people": 2,
    }

    serializer = CartItemSerializer(data=valid_payload)
    assert serializer.is_valid(), serializer.errors
    assert "model_type" in serializer.validated_data


# --- 2. BOOKING SERIALIZER TESTS ---

@pytest.mark.django_db
def test_booking_and_item_serializers(new_booking_item, new_user):
    """Tests the combined nested representation output for Booking\
          & BookingItem models."""
    user_instance = new_user(username="booking_customer_alpha")
    user_instance.save()

    customer_profile = CustomerModel.objects.create(user=user_instance)

    # Instantiate Booking directly to bypass the broken conftest fixture fallback
    booking = BookingModel.objects.create(customer=customer_profile)

    mock_service = VendorModel.objects.create(company_name="Booked Service Target")

    item = new_booking_item(booking=booking, content_object=mock_service, days=3)
    item.save()

    serializer = BookingSerializer(instance=booking)
    data = serializer.data

    assert data["id"] == booking.id
    assert data["customer_username"] == "booking_customer_alpha"
    assert len(data["items"]) == 1
    assert data["items"][0]["days"] == 3


@pytest.mark.django_db
def test_booking_item_serializer_fields(new_user):
    """Tests the standalone field layout outputs of serialized BookingItems."""
    user_instance = new_user(username="booking_item_customer")
    user_instance.save()

    customer_profile = CustomerModel.objects.create(user=user_instance)
    booking = BookingModel.objects.create(customer=customer_profile)

    mock_service = VendorModel.objects.create(company_name="Isolated Booking Item View")
    item = BookingItemSerializer().to_representation(
        apps.get_model("order", "BookingItem")(booking=booking,
                                               content_object=mock_service,
                                               days=7)
    )

    assert item["days"] == 7


# --- 3. SMS OUTGOING QUEUE SERIALIZER TESTS ---

@pytest.mark.django_db
def test_sms_outgoing_queue_serializer(new_sms_outgoing, new_user):
    """Checks interface payloads generated by outbound hardware lanes."""
    user_instance = new_user(username="sms_customer")
    user_instance.save()

    customer_profile = CustomerModel.objects.create(user=user_instance)
    booking = BookingModel.objects.create(customer=customer_profile)

    sms = new_sms_outgoing(booking=booking, phone_number="+2399901234",
                           message_text="Invoice Link",
                           is_sent=True)
    sms.save()

    serializer = SMSOutgoingQueueSerializer(instance=sms)
    data = serializer.data

    assert data["id"] == sms.id
    assert data["phone_number"] == "+2399901234"
    assert data["message_text"] == "Invoice Link"
    assert data["is_sent_by_phone"] is True


# --- 4. REVIEWS & FEEDBACK SERIALIZER TESTS ---

@pytest.mark.django_db
def test_review_serializer(monkeypatch, new_user):
    """Tests review object serialization lifecycle without hardcoded static imports."""
    user_instance = new_user(username="reviewer_alpha")
    user_instance.save()

    customer = CustomerModel.objects.create(user=user_instance)

    mock_service = VendorModel.objects.create(company_name="Reviewed Service")
    vendor_content_type = ContentType.objects.get_for_model(VendorModel)

    monkeypatch.setattr(
        ReviewSerializer,
        "validate_model_type",
        lambda self, value: vendor_content_type
    )

    valid_payload = {
        "content": "Had an incredible experience with this service vendor!",
        "rating": 5,
        "model_type": "vendor",
        "object_id": mock_service.id,
    }

    serializer = ReviewSerializer(data=valid_payload)
    assert serializer.is_valid(), serializer.errors

    review = serializer.save(customer=customer)

    assert review.id is not None
    assert review.customer == customer
    assert review.content == "Had an incredible experience with this service vendor!"
    assert review.rating == 5

    outbound_serializer = ReviewSerializer(instance=review)
    data = outbound_serializer.data

    assert data["customer_username"] == "reviewer_alpha"
    assert data["content"] == "Had an incredible experience with this service vendor!"
