# Generated by Django 4.2.7 on 2024-03-17 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiuldingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prefix', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cemiterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=255, null=True)),
                ('date_issue', models.DateTimeField(auto_now=True, null=True)),
                ('text', models.TextField(default='', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='camaramz/certificates')),
                ('status', models.CharField(choices=[('C', 'Concluído'), ('F', 'Incorrecto'), ('P', 'Pendente'), ('R', 'Revisto'), ('A', 'Archived')], default='P', max_length=1, null=True)),
                ('obs', models.TextField(null=True)),
                ('atestado_state', models.IntegerField(default=1, null=True)),
                ('type_id1', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('o', 'o'), ('a', 'a')], default='o', max_length=1, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('code', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.country')),
            ],
        ),
        migrations.CreateModel(
            name='Coval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_number', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_used', models.DateField()),
                ('date_of_deth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('square', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1)),
                ('closed', models.BooleanField(default=False)),
                ('selled', models.BooleanField(default=False)),
                ('cemiterio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='certificates.cemiterio')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IDType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ifen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instituition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('text', models.TextField()),
                ('sent', models.BooleanField(blank=True, default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('in_plural', models.CharField(max_length=255)),
                ('in_plural_mix', models.CharField(max_length=255)),
                ('degree', models.IntegerField(default=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.county')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.county')),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.town')),
            ],
        ),
        migrations.CreateModel(
            name='PersonBirthAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='birth_person_address', to='certificates.country')),
                ('birth_county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birth_person_address', to='certificates.county')),
                ('birth_street', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birth_person_address', to='certificates.street')),
                ('birth_town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birth_person_address', to='certificates.town')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(default='', max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_day', models.IntegerField(null=True)),
                ('birth_month', models.IntegerField(null=True)),
                ('birth_year', models.IntegerField(null=True)),
                ('bi_nasc_loc', models.IntegerField(null=True)),
                ('id_number', models.CharField(max_length=255)),
                ('id_issue_date', models.DateField(null=True)),
                ('id_issue_day', models.IntegerField(default=1, null=True)),
                ('id_issue_month', models.IntegerField(default=1, null=True)),
                ('id_issue_year', models.IntegerField(default=1, null=True)),
                ('id_expire_date', models.DateField(null=True)),
                ('father_name', models.CharField(max_length=255, null=True)),
                ('mother_name', models.CharField(max_length=255, null=True)),
                ('bi_estado', models.IntegerField(null=True)),
                ('bi_sexo', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('M', 'Married'), ('S', 'Single'), ('L', 'Living together'), ('V', 'Viuvo'), ('D', 'Divorcied')], max_length=1, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person', to='certificates.house')),
                ('birth_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='certificates.personbirthaddress')),
                ('id_issue_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_issue_person', to='certificates.country')),
                ('id_issue_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_issue_person', to='certificates.instituition')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.idtype')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_nationality', to='certificates.country')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.street'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CovalSalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.coval')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.person')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('goal', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('certificate_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.certificatetypes')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateSinglePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificatetitle')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateSimplePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Femal')], max_length=1)),
                ('birth_date', models.DateField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificatetitle')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateSimpleParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.parent')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificatetitle')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificatetitle')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificate')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.house')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.house'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='main_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_person_certificates', to='certificates.person'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='secondary_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_person_certificates', to='certificates.person'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.certificatetitle'),
        ),
        migrations.AddField(
            model_name='cemiterio',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.county'),
        ),
    ]
