# Generated by Django 5.0.6 on 2024-12-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_issue',
            field=models.DateTimeField(null=True),
        ),
    ]
