# Generated by Django 5.0.6 on 2024-12-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_alter_certificate_date_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_issue',
            field=models.DateTimeField(null=True),
        ),
    ]
