# Generated by Django 5.0.6 on 2024-12-31 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_certificate_date_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='date_issue',
        ),
    ]
