# Generated by Django 5.0.6 on 2024-12-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_remove_certificate_date_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='date_issue',
            field=models.DateTimeField(null=True),
        ),
    ]
