# Generated by Django 5.0.6 on 2024-12-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0010_certificate_date_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_issue',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
