# Generated by Django 5.1.7 on 2025-07-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0012_alter_country_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'Basic'), ('M', 'Medium'), ('C', 'Average')], max_length=1, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
