# Generated by Django 5.0 on 2025-12-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0013_certificaterange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetitle',
            name='goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificatetitle',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
