# Generated by Django 5.0 on 2026-03-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0014_alter_certificatetitle_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='backstaff',
            field=models.BooleanField(default=False),
        ),
    ]
