# Generated by Django 5.0 on 2026-04-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0015_customer_backstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_issue',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='number',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.TextField(choices=[('C', 'Concluído'), ('F', 'Incorrecto'), ('P', 'Pendente'), ('R', 'Revisto'), ('A', 'Archived')], db_index=True, default='P', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='father_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.TextField(choices=[('M', 'Male'), ('F', 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_issue_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.TextField(choices=[('M', 'Married'), ('S', 'Single'), ('L', 'Living together'), ('V', 'Viuvo'), ('D', 'Divorcied')], null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.TextField(db_index=True, default=''),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['number', 'status'], name='certificate_number_b08363_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name', 'surname'], name='certificate_name_d00065_idx'),
        ),
    ]
