# Generated by Django 5.0 on 2026-05-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0016_alter_certificate_date_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='type_id1',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
