# Generated by Django 5.0 on 2026-06-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_booking_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='user',
        ),
    ]
