# Generated by Django 4.2.7 on 2024-03-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_alter_usertokens_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokens',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
