"""
Django settings for camaramz project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import sys
import os
from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR.parent))
import dj_database_url

# 1. Safely resolve boolean evaluation to prevent text quote bugs
raw_debug = os.environ.get("DEBUG", "0").replace('"', '').replace("'", "").strip()
DEBUG = raw_debug in ["True", "1"]

SECRET_KEY = os.environ.get("SECRET_KEY", "fallback_change_me").replace('"', '').replace("'", "").strip()

# 2. Clean and parse host array allowances
raw_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost 127.0.0.1 .localhost")
cleaned_hosts = raw_hosts.replace('"', '').replace("'", "").strip()
ALLOWED_HOSTS = cleaned_hosts.split(" ")

# 3. Clean and parse trusted origins whitelists
raw_origins = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
cleaned_origins = raw_origins.replace('"', '').replace("'", "").strip()
CSRF_TRUSTED_ORIGINS = cleaned_origins.split(" ")

# 4. Clean cookie security bounds explicitly
SESSION_COOKIE_DOMAIN = os.environ.get("SESSION_COOKIE_DOMAIN", ".teladoshi.com")
CSRF_COOKIE_DOMAIN = os.environ.get("CSRF_COOKIE_DOMAIN", ".teladoshi.com")

if SESSION_COOKIE_DOMAIN: 
    SESSION_COOKIE_DOMAIN = SESSION_COOKIE_DOMAIN.replace('"', '').replace("'", "").strip()
if CSRF_COOKIE_DOMAIN: 
    CSRF_COOKIE_DOMAIN = CSRF_COOKIE_DOMAIN.replace('"', '').replace("'", "").strip()

# 5. Boolean flags evaluation for cookies
SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", "False").replace('"', '') == "True"
CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", "False").replace('"', '') == "True"
SESSION_COOKIE_HTTPONLY = os.environ.get("SESSION_COOKIE_HTTPONLY", "True").replace('"', '') == "True"

if DEBUG: 
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


SHARED_APPS = (
    "modeltranslation",

    'django_tenants',  # mandatory
    'core',  # you must list the app where your tenant model resides in

    'django.contrib.contenttypes',

    # everything below here is optional
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_filters",
    "corsheaders",
    "djoser",
    "setup",
    "storages",
    "mail_templated",
    "drf_spectacular",
)

TENANT_APPS = (
    # your tenant-specific apps
    "teladoshi",
    "order",
)

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]



TENANT_MODEL = "core.Client" # app.Model

TENANT_DOMAIN_MODEL = "core.Domain"  # app.Model



MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    
    # 1. First, initialize the session
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    
    # 2. Second, authenticate the user (creates request.user)
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    # 3. Third, run your custom security guard (uses request.user safely)
    'core.middleware.TenantSecurityMiddleware',  
    
    # 4. Fourth, validate CSRF tokens
    'django.middleware.csrf.CsrfViewMiddleware',
    
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


LANGUAGES = (
    ("pt", "Portuguese"),
    ("en", "English"),
    ("fr", "French"),
)

# 3. Choose the fallback language if a specific translation doesn't exist
MODELTRANSLATION_DEFAULT_LANGUAGE = "en"
MODELTRANSLATION_FALLBACK_LANGUAGES = ("en",'fr',"pt")



ROOT_URLCONF = 'camaramz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'camaramz.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

AUTH_USER_MODEL = "core.User"



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",  # User uploads -> S3
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",  # CSS/JS -> Local
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)
AUTHENTICATION_BACKENDS = [
    'core.backends.SharedModelTenantBackend', # Points to your newly created class
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'core.backends.MultiTenantJWTAuthentication', # Replaces standard SimpleJWT class
        'rest_framework.authentication.SessionAuthentication', # Kept for admin panel stability
    ),
}

# 3. Configure SimpleJWT to use your token claim serializer
SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("JWT",),
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    'TOKEN_OBTAIN_PAIR_SERIALIZER': 'core.serializers.TenantTokenObtainPairSerializerNew',
}

# 4. Bind Djoser configuration settings
DJOSER = {
    "SET_PASSWORD_RETYPE": True,
    "SET_USERNAME_RETYPE": True,
    "PASSWORD_RESET_CONFIRM_URL": "auth/reset-password/{uid}/{token}",
    "PASSWORD_RESET_CONFIRM_RETYPE": True,
    "PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND": True,
    'LOGIN_FIELD': 'email',
    'USER_ID_FIELD': 'id',
    "SERIALIZERS": {
        "user_create": "core.serializers.CustomUserCreateSerializer",
        "user": "core.serializers.CustomUserSerializer",
        "current_user": "core.serializers.CustomUserSerializer",
        "token_create": "core.serializers.TenantTokenObtainPairSerializerNew",
        "set_password_retype": "core.serializers.SetPasswordRetypeSerializer",
        "set_username": "core.serializers.SetUsernameSerializer",
        "password_reset": "core.serializers.SendEmailResetSerializer",
        "password_reset_confirm_retype": "core.serializers.PasswordResetConfirmRetypeSerializer",
    },
}

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_METADATA_CLASS': None,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "COERCE_DECIMAL_TO_STRING": False,
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
# Spectacular Settings atualizado para JWT
SPECTACULAR_SETTINGS = {
    'TITLE': 'Government Multi-Tenant Kernel API',
    'DESCRIPTION': (
        'Centralized Backend Engine for Municipal Management and NGO Services. '
        'Analytical & Automation Workflows with JWT Authentication and Tenant isolation.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'CONTACT': {
        'name': 'Edmilbe Ramos',
        'email': 'bm.edmilbe@gmail.com',
    },
    'APPEND_COMPONENTS': {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    'SECURITY': [
        {
            "BearerAuth": [],
        }
    ],
}
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "edmilbe@gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

ADMINS = [("Ramos", "admin@hotmail.com")]
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
        "file": {
            "class": "logging.FileHandler",
            "filename": "general.log",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console", "file"],
            "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
        }
    },
    "formatters": {
        "verbose": {
            "format": "{asctime} ({levelname}) - {name} - {message}",
            "style": "{",
        }
    },
}


SILENCED_SYSTEM_CHECKS = ["auth.E003", "auth.W004"]
DATABASE_URL = os.environ.get("DATABASE_URL","")
DATABASE_ENGINE = os.environ.get("DATABASE_ENGINE","")
DATABASES = {
    "default": dj_database_url.config(
        default=DATABASE_URL, 
        conn_max_age=600,
        engine=DATABASE_ENGINE
    )
}
TOUR_WEBSITE = os.environ.get("WEBSITE","")
TOUR_EMAIL = os.environ.get("EMAIL","")
TOUR_TITLE = os.environ.get("TITLE","")
TOUR_EMAIL_HOST_PASSWORD = os.environ.get("TOUR_EMAIL_HOST_PASSWORD")
TOUR_LOGO = os.environ.get("LOGO", "")
TOUR_EMAIL_DATA = {
        "EMAIL": TOUR_EMAIL,
        "TITLE": TOUR_TITLE,
        "PASSWORD": TOUR_EMAIL_HOST_PASSWORD,
        "WEBSITE": TOUR_WEBSITE,
        "LOGO": TOUR_LOGO
}



AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "")
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME", "")
AWS_S3_REGION_NAME = "eu-north-1"
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_DEFAULT_ACL = None
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
AWS_S3_FILE_OVERWRITE = False